ace.define("ace/theme/apsys", ["require", "exports", "module", "ace/lib/dom"], function (e, t, n) {
	
    t.isDark = !1, t.cssClass = "ace-apsys", t.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: EE3AD170-2B7F-4DE1-B724-C75F13FE0085) */\
    .ace-apsys .ace_gutter {\
    	background: #e8e8e8;\
    	color: #333\
    }\
    .ace-apsys .ace_print-margin {\
    	width: 1px;\
    	background: transparent\
    }\
    .ace-apsys .ace_scroller {\
    	background-color: #FFFFFF\
    }\
    .ace-apsys .ace_text-layer {\
    	color: #000000\
    }\
    .ace-apsys .ace_cursor {\
    	border-left: 2px solid #000000\
    }\
    .ace-apsys .ace_overwrite-cursors .ace_cursor {\
    	border-left: 0px;\
    	border-bottom: 1px solid #000000\
    }\
    .ace-apsys .ace_marker-layer .ace_selection {\
    	background: #B5D5FF\
    }\
    .ace-apsys.ace_multiselect .ace_selection.ace_start {\
    	box-shadow: 0 0 3px 0px #FFFFFF;\
    	border-radius: 2px\
    }\
    .ace-apsys .ace_marker-layer .ace_step {\
    	background: rgb(198, 219, 174)\
    }\
    .ace-apsys .ace_marker-layer .ace_bracket {\
    	margin: -1px 0 0 -1px;\
    	border: 1px solid #BFBFBF\
    }\
    .ace-apsys .ace_marker-layer .ace_active-line {\
    	background: rgba(0, 0, 0, 0.071)\
    }\
    .ace-apsys .ace_gutter-active-line {\
    	background-color: rgba(0, 0, 0, 0.071)\
    }\
    .ace-apsys .ace_marker-layer .ace_selected-word {\
    	border: 1px solid #B5D5FF\
    }\
    .ace-apsys .ace_constant.ace_language,.ace-apsys .ace_meta,\n\
        .ace-apsys .ace_variable.ace_language {\
        	color: red\
        }\
    .ace-apsys .ace_keyword {\
    	color: blue\
    }\
    .ace-apsys .ace_invisible {\
    	color: #BFBFBF\
    }\
    .ace-apsys .ace_constant.ace_character,.ace-apsys .ace_constant.ace_other {\
    	color: #275A5E\
    }\n\
    .ace-apsys .ace_constant.ace_numeric {\
    	color: red\
    }\
    .ace-apsys .ace_entity.ace_other.ace_attribute-name,.ace-apsys .ace_support.ace_constant,\n\
    .ace-apsys .ace_support.ace_function {\
    	color: #00A37A\
    }\
    .ace-apsys .ace_fold {\
    	background-color: #C800A4;\
    	border-color: #000000\
    }\
    .ace-apsys .ace_entity.ace_name.ace_tag,.ace-apsys .ace_support.ace_class,.ace-apsys .ace_support.ace_type {\
    	color: #790EAD\
    }\n\
    .ace-apsys .ace_storage {\
    	color: red\
    }\
    .ace-apsys .ace_string {\
    	color: #DF0002\
    }\
    .ace-apsys .ace_comment {\
    	color: #008E00\
    }\
    .ace-apsys .ace_indent-guide {\
    	background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAE0lEQVQImWP4////f4bLly//BwAmVgd1/w11/gAAAABJRU5ErkJggg==) right repeat-y;\
    }";
    var r = e("../lib/dom");
    r.importCssString(t.cssText, t.cssClass)
})
//alice modify color: red and blue